# Generated by Django 5.0.3 on 2024-04-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangManApp', '0002_user_remove_score_id_alter_score_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='member',
        ),
    ]
