# Generated by Django 5.0.3 on 2024-04-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangManApp', '0004_rename_member_score_member_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='member_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HangManApp.member'),
        ),
    ]
