# Generated by Django 5.0.3 on 2024-04-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangManApp', '0005_alter_score_member_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Game',
        ),
    ]
